# Generated by Django 5.2.17 on 2026-08-28 12:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('date_applied', models.DateField(default=django.utils.timezone.now)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('purpose', models.CharField(blank=True, default='', max_length=500)),
                ('voucher_no', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=4.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('loan_term', models.PositiveIntegerField(default=12, help_text='Loan term in months')),
                ('moratorium', models.PositiveIntegerField(default=0, help_text='Moratorium period in months')),
                ('disbursement_date', models.DateField(default=django.utils.timezone.now)),
                ('date_approved', models.DateField(default=django.utils.timezone.now)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('next_repayment_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('New Loan', 'New Loan'), ('Active', 'Active'), ('Owing', 'Owing'), ('Completed', 'Completed'), ('Expired', 'Expired'), ('Credit', 'Credit')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guarantor_data', models.JSONField(blank=True, default=dict, null=True)),
                ('master_avail_bal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('loan_class', models.CharField(choices=[('Current', 'Current'), ('OLEM', 'OLEM'), ('Substandard', 'Substandard'), ('Doubtfull', 'Doubtfull'), ('Loss', 'Loss')], default='Current', max_length=15)),
                ('loan_class_calc', models.CharField(choices=[('Current', 'Current'), ('OLEM', 'OLEM'), ('Substandard', 'Substandard'), ('Doubtfull', 'Doubtfull'), ('Loss', 'Loss')], default='', max_length=15)),
                ('tot_int', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('tot_ded', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('months_remain', models.IntegerField(default=0)),
                ('payment_status', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('loan_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('due_days', models.IntegerField(blank=True, default=0, null=True)),
                ('due_interest', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('due_repayment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('due_tot_repayment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('due_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('overdue_days', models.IntegerField(blank=True, null=True)),
                ('loan_trans_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('loan_upd_indicator', models.BooleanField(default=False)),
                ('last_interest_calculation_date', models.DateField(blank=True, null=True)),
                ('last_penalty_calculation_date', models.DateField(blank=True, null=True)),
                ('repayment_overdue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('interest_overdue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('penalty_accrued', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_interest_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('last_repayment_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('next_payment_due_date', models.DateField(blank=True, null=True)),
                ('last_due_date', models.DateField(blank=True, default=None, null=True)),
                ('loan_update_cnt', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_credit_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDefaultInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_full_name', models.CharField(max_length=150)),
                ('old_loan_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_loan_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_added', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_repayment_date', models.DateField(blank=True, default=None, null=True)),
                ('next_repayment_date', models.DateField(blank=True, default=None, null=True)),
                ('overdue_days', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanInterestAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('next_repayment_date', models.DateField()),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('months', models.IntegerField(default=1)),
                ('interest_accrued', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expiry_date', models.DateField()),
                ('loan_class', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('trans_date', models.DateField(blank=True, null=True)),
                ('old_loan_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('new_loan_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gua_redeemed_details', models.JSONField(blank=True, default=dict)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('repayment_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.IntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['installment_no'],
            },
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DISBURSEMENT', 'Loan Disbursement'), ('REPAYMENT', 'Loan Repayment'), ('INTEREST', 'Interest Accrual'), ('PENALTY', 'Penalty')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('guaranteed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('guaranteed_date', models.DateField(default=django.utils.timezone.now)),
                ('redeemed_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('redeemed_status', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_gua', to='django_ledger.entitymodel')),
            ],
        ),
    ]
