# Generated by Django 5.2.17 on 2026-08-28 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoanApp', '0001_initial'),
        ('MembersApp', '0001_initial'),
        ('django_ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MembersApp.master'),
        ),
        migrations.AddField(
            model_name='loan',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_entity', to='django_ledger.entitymodel'),
        ),
        migrations.AddField(
            model_name='loan',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='MembersApp.master'),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='LoanApp.loan'),
        ),
        migrations.AddField(
            model_name='loandefaultinterest',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_default', to='django_ledger.entitymodel'),
        ),
        migrations.AddField(
            model_name='loandefaultinterest',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_interests', to='LoanApp.loan'),
        ),
        migrations.AddField(
            model_name='loandefaultinterest',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MembersApp.master'),
        ),
        migrations.AddField(
            model_name='loaninterestaudit',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loan'),
        ),
        migrations.AddField(
            model_name='loaninterestaudit',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MembersApp.master'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_rep', to='django_ledger.entitymodel'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='LoanApp.loan'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayments', to='MembersApp.master'),
        ),
    ]
