# Generated by Django 5.2.6 on 2026-09-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='master',
            new_name='member',
        ),
    ]
