# Generated by Django 5.2.6 on 2026-08-01 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0003_loan_entity'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_gua', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandefaultinterest',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_default', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_rep', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanschedule',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_sche', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_trans', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
    ]
