# Generated by Django 5.2.6 on 2026-09-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0004_rename_master_loan_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
