# Generated by Django 5.2.6 on 2026-08-15 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0004_guarantor_entity_loandefaultinterest_entity_and_more'),
        ('MembersApp', '0012_master_tot_sav_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInterestAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('next_repayment_date', models.DateField()),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('months', models.IntegerField(default=1)),
                ('interest_accrued', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expiry_date', models.DateField()),
                ('loan_class', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoanApp.loan')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MembersApp.master')),
            ],
        ),
    ]
