# Generated by Django 5.2.6 on 2026-09-23 02:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0005_loan_loan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Monthly penalty rate (%) on overdue principal', max_digits=6),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=4.0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
