# Generated by Django 5.2.6 on 2026-09-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0006_loan_penalty_rate_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_term',
            new_name='term_months',
        ),
    ]
