# Generated by Django 5.2.6 on 2026-09-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0007_rename_loan_term_loan_term_months'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='disbursement_date',
            new_name='date_disbursed',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='moratorium',
            new_name='moratorium_months',
        ),
    ]
