# Generated by Django 5.2.6 on 2026-09-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0008_rename_disbursement_date_loan_date_disbursed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_accrual_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='maturity_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
