# Generated by Django 5.2.6 on 2026-09-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0009_loan_last_accrual_date_loan_maturity_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='next_payment_due_date',
            new_name='next_payment_date',
        ),
    ]
