# Generated by Django 5.2.6 on 2026-09-23 05:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0010_rename_next_payment_due_date_loan_next_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('NEW', 'New (Applied)'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WRITTEN_OFF', 'Written Off')], default='NEW', max_length=20),
        ),
    ]
