# Generated by Django 5.2.6 on 2026-09-23 05:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0011_loan_balance_alter_loan_status'),
        ('RecPayApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursement_trans',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loan', to='RecPayApp.trans'),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='member_balance_at_application',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
