# Generated by Django 5.2.6 on 2026-09-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0012_loan_disbursement_trans_loan_interest_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-date_applied', '-id']},
        ),
    ]
