# Generated by Django 5.2.6 on 2026-09-23 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0013_alter_loan_options'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='master',
            new_name='member',
        ),
        migrations.CreateModel(
            name='GuarantorRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_released', models.DecimalField(decimal_places=2, max_digits=15)),
                ('holding_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('holding_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_releases', to='django_ledger.entitymodel')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_history', to='LoanApp.guarantor')),
                ('repayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_releases', to='LoanApp.loanrepayment')),
            ],
        ),
    ]
