# Generated by Django 5.2.6 on 2026-09-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0014_rename_master_loanrepayment_member_guarantorrelease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='trans_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
