# Generated by Django 5.2.6 on 2026-09-23 07:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0015_rename_trans_date_loanrepayment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='new_loan_balance',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='old_loan_balance',
            new_name='balance_after',
        ),
        migrations.RenameField(
            model_name='loanrepayment',
            old_name='trans_amount',
            new_name='balance_before',
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='penalty_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
