# Generated by Django 5.2.6 on 2026-09-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0016_rename_new_loan_balance_loanrepayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
