# Generated by Django 5.2.6 on 2026-09-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0017_alter_loanrepayment_notes'),
        ('MembersApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantor',
            name='master',
        ),
        migrations.AddField(
            model_name='guarantor',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guarantees_given', to='MembersApp.master'),
            preserve_default=False,
        ),
    ]
