# Generated by Django 5.2.6 on 2026-09-23 18:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0018_remove_guarantor_master_guarantor_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount this member has pledged.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
