# Generated by Django 5.2.6 on 2026-09-23 18:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0019_guarantor_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='called_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='guarantor',
            name='released_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
