# Generated by Django 5.2.6 on 2026-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0020_guarantor_called_amount_guarantor_released_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
    ]
