# Generated by Django 5.2.6 on 2026-09-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0021_guarantor_created_at'),
        ('MembersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guarantor',
            options={'ordering': ['date', 'id']},
        ),
        migrations.AddField(
            model_name='guarantor',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='guarantor',
            unique_together={('loan', 'member')},
        ),
    ]
