# Generated by Django 5.2.6 on 2026-09-23 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0022_alter_guarantor_options_guarantor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
