# Generated by Django 5.2.6 on 2026-09-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0023_alter_guarantor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
