# Generated by Django 5.2.6 on 2026-09-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0024_alter_guarantor_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantor',
            name='guaranteed_amount',
        ),
        migrations.RemoveField(
            model_name='guarantor',
            name='guaranteed_date',
        ),
    ]
