# Generated by Django 5.2.6 on 2026-09-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0025_remove_guarantor_guaranteed_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantor',
            name='guarantor_name',
        ),
        migrations.RemoveField(
            model_name='guarantor',
            name='redeemed_amount',
        ),
        migrations.RemoveField(
            model_name='guarantor',
            name='redeemed_status',
        ),
    ]
