# Generated by Django 5.2.6 on 2026-09-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0026_remove_guarantor_guarantor_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanrepayment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='gua_redeemed_details',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='repayment_paid',
        ),
    ]
