# Generated by Django 5.2.6 on 2026-09-23 19:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0027_alter_loanrepayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanschedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='loanschedule',
            name='installment_no',
        ),
        migrations.RemoveField(
            model_name='loanschedule',
            name='loan',
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_accrued',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
