# Generated by Django 5.2.6 on 2026-09-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0028_alter_loanschedule_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanSchedule',
        ),
    ]
