# Generated by Django 5.2.6 on 2026-09-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0029_delete_loanschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanTransaction',
        ),
    ]
