# Generated by Django 5.2.6 on 2026-09-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0031_delete_loaninterestaudit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanDefaultInterest',
        ),
    ]
