# Generated by Django 5.2.6 on 2026-09-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0032_delete_loandefaultinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('New Loan', 'New Loan'), ('Active', 'Active'), ('Owing', 'Owing'), ('Completed', 'Completed'), ('Expired', 'Expired'), ('Credit', 'Credit')], default='NEW', max_length=20),
        ),
    ]
