# Generated by Django 5.2.6 on 2026-09-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0033_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partially Released'), ('RELEASED', 'Released'), ('CALLED', 'Called')], default='ACTIVE', max_length=20),
        ),
    ]
