# Generated by Django 5.2.6 on 2026-09-23 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0034_alter_guarantor_status'),
        ('MembersApp', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInterestAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('next_repayment_date', models.DateField()),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('months', models.IntegerField(default=1)),
                ('interest_accrued', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('loan_class', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_interest_audits', to='django_ledger.entitymodel')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_audits', to='LoanApp.loan')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_interest_audits', to='MembersApp.master')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('loan', 'next_repayment_date')},
            },
        ),
    ]
