# Generated by Django 5.2.6 on 2026-09-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0036_loan_created_by_alter_loan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
