# Generated by Django 5.2.6 on 2026-09-25 06:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0037_alter_loan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='due_interest_at_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
