# Generated by Django 5.2.6 on 2026-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0038_loanrepayment_due_interest_at_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='pending_releases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='posted',
            field=models.BooleanField(default=False, help_text='True once a supervisor has posted the linked Trans.'),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='due_interest_at_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Loan.due_interest snapshot at the moment of this repayment.', max_digits=15),
        ),
    ]
