# Generated by Django 5.2.6 on 2026-09-26 03:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0039_loanrepayment_pending_releases_loanrepayment_posted_and_more'),
        ('MembersApp', '0004_remove_master_tot_interest_accrued'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLoanTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('due_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('due_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_part', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('repayment_part', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_due_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_due_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_interest_entity', to='django_ledger.entitymodel')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_loan_table', to='LoanApp.loan')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_interest_master', to='MembersApp.master')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['loan', '-date'], name='LoanApp_dai_loan_id_da17c1_idx')],
                'unique_together': {('loan', 'date')},
            },
        ),
    ]
