# Generated by Django 5.2.17 on 2026-08-28 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coreapp_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('SAVINGS_INTEREST', 'Savings Interest Accrual'), ('LOAN_INTEREST', 'Loan Interest Calculation'), ('LOAN_PENALTY', 'Loan Penalty Calculation'), ('DAILY_REPORT', 'Daily Report Generation'), ('BACKUP', 'Database Backup'), ('STATEMENT', 'Member Statement Generation'), ('DIVIDEND', 'Dividend Calculation'), ('YEAR_END', 'Year End Closing')], max_length=50, unique=True)),
                ('process_name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('last_run_message', models.TextField(blank=True)),
                ('next_run_due', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.IntegerField(default=0)),
                ('successful_runs', models.IntegerField(default=0)),
                ('failed_runs', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_processes', to=settings.AUTH_USER_MODEL)),
                ('last_run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_run_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['process_name'],
            },
        ),
        migrations.CreateModel(
            name='BatchProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('error_details', models.TextField(blank=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='CoreApp.batchprocess')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(max_length=200)),
                ('backup_file', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('tables_backup', models.TextField(blank=True, help_text='List of tables backed up')),
                ('backup_started', models.DateTimeField(auto_now_add=True)),
                ('backup_completed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-backup_started'],
            },
        ),
    ]
