# Generated by Django 5.2.6 on 2026-08-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysSetup', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aud_log', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fisc_Period', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systempreference',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sys_pref', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sys_set', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
    ]
