# Generated by Django 5.2.6 on 2026-08-03 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysSetup', '0002_auditlog_entity_fiscalperiod_entity_and_more'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aud_log', to='django_ledger.entitymodel'),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fisc_Period', to='django_ledger.entitymodel'),
        ),
        migrations.AlterField(
            model_name='systempreference',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sys_set', to='django_ledger.entitymodel'),
        ),
    ]
