# Generated by Django 5.2.6 on 2026-08-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SysSetup', '0003_alter_auditlog_entity_alter_fiscalperiod_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='fiscalperiod',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='systempreference',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='entity',
        ),
    ]
