# Generated by Django 5.2.6 on 2026-08-03 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysSetup', '0004_remove_auditlog_entity_remove_fiscalperiod_entity_and_more'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aud_log', to='django_ledger.entitymodel'),
        ),
    ]
