# Generated by Django 5.2.6 on 2026-08-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SysSetup', '0005_auditlog_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='entity',
        ),
    ]
