# Generated by Django 5.2.17 on 2026-08-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_user_management', 'Can view user management'), ('can_manage_users', 'Can add, edit, delete users'), ('can_view_backup', 'Can access backup and restore'), ('can_perform_factory_reset', 'Can perform factory reset'), ('can_view_reports', 'Can view financial reports')],
                'managed': False,
            },
        ),
    ]
