# Generated by Django 5.2.16 on 2026-07-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Report Name')),
                ('table_name', models.CharField(max_length=50, verbose_name='Table Name')),
                ('selected_fields', models.TextField(verbose_name='Selected Fields')),
                ('filters', models.TextField(blank=True, null=True, verbose_name='Filters')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
