# Generated by Django 5.2.6 on 2026-08-11 00:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('depreciation_method', models.CharField(choices=[('SL', 'Straight-Line'), ('RB', 'Reducing Balance')], default='SL', max_length=20)),
                ('useful_life_years', models.IntegerField(help_text='Useful life in years')),
                ('salvage_value_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='As % of cost', max_digits=5)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Annual depreciation rate (%) for reducing balance method. Not used for straight‑line.', max_digits=5)),
                ('accumulated_depreciation_account', models.ForeignKey(blank=True, help_text='GL account for accumulated depreciation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories_acc_dep', to='django_ledger.accountmodel')),
                ('asset_account', models.ForeignKey(blank=True, help_text='GL account for asset cost', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories_asset', to='django_ledger.accountmodel')),
                ('depreciation_expense_account', models.ForeignKey(blank=True, help_text='GL account for depreciation expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories_dep_exp', to='django_ledger.accountmodel')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_assets', to='django_ledger.entitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('override_depreciation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional override rate (e.g., 20%)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acquisition_date', models.DateField()),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance')], default='straight_line', max_length=20)),
                ('useful_life_years', models.PositiveIntegerField(default=5)),
                ('categoryaccount', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('last_depreciation_date', models.DateField(blank=True, default=None, null=True)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FixedAssets.assetcategory')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='django_ledger.entitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depreciation', to='django_ledger.entitymodel')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries', to='django_ledger.journalentrymodel')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='FixedAssets.fixedasset')),
            ],
        ),
    ]
