# Generated by Django 5.2.6 on 2026-09-22 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FixedAssets', '0001_initial'),
        ('RecPayApp', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depreciationentry',
            name='trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries', to='RecPayApp.trans'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='FixedAssets.assetcategory'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='django_ledger.entitymodel'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='RecPayApp.trans'),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='FixedAssets.fixedasset'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together={('entity', 'name')},
        ),
    ]
