# Generated by Django 5.2.6 on 2026-08-11 03:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixedAssets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='accumulated_depreciation',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
    ]
