# Generated by Django 5.2.6 on 2026-10-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixedAssets', '0002_initial'),
        ('RecPayApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='last_dep_trans',
            field=models.ForeignKey(blank=True, help_text='The most recent depreciation Trans linked to this asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciated_asset', to='RecPayApp.trans'),
        ),
    ]
