# Generated by Django 5.2.6 on 2026-10-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FixedAssets', '0003_fixedasset_last_dep_trans'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixedasset',
            unique_together={('entity', 'asset_id')},
        ),
    ]
