# Generated by Django 5.2.6 on 2026-10-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixedAssets', '0004_alter_fixedasset_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='bank_account_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='cheque_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('MOMO', 'Mobile Money'), ('CREDIT', 'Credit / Payable')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='seller_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='seller_contact',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='seller_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
