# Generated by Django 5.2.6 on 2026-08-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statejournalentry',
            name='original_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statejournalentry',
            name='posted_by_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statejournalentry',
            name='source_trans_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statejournalline',
            name='member_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statejournalline',
            name='original_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
