# Generated by Django 5.2.6 on 2026-08-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_statejournalentry_original_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statejournalentry',
            name='original_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statejournalentry',
            name='posted_by_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statejournalentry',
            name='source_trans_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statejournalline',
            name='member_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statejournalline',
            name='original_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
