# Generated by Django 5.2.6 on 2026-09-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditUnionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_loan_term', models.PositiveIntegerField(default=36)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('moratorium_days', models.PositiveIntegerField(default=0)),
                ('loan_interest_rate', models.DecimalField(decimal_places=4, default=0, help_text='Annual interest rate (%)', max_digits=8)),
                ('loan_asset_account_code', models.CharField(default='1080', max_length=20)),
                ('loan_interest_income_code', models.CharField(default='4010', max_length=20)),
                ('min_savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('savings_frequency', models.CharField(default='monthly', max_length=20)),
                ('savings_interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('savings_interest_application', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('savings_calc_type', models.CharField(choices=[('Simple_Sav_Interest', 'Simple'), ('Compound_Sav_Interest', 'Compound')], default='Simple_Sav_Interest', max_length=30)),
                ('sav_int_appl', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='', max_length=20, null=True)),
                ('last_interest_accrual_date', models.DateField(blank=True, null=True)),
                ('last_interest_accrual_run', models.DateTimeField(blank=True, null=True)),
                ('interest_expense_account_code', models.CharField(default='5020', max_length=20)),
                ('savings_interest_payable_account_code', models.CharField(default='2020', max_length=20)),
                ('membership_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('min_shares', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cu_config', to='django_ledger.entitymodel')),
            ],
        ),
    ]
