# Generated by Django 5.2.6 on 2026-09-22 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FinanceApp', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, default='', max_length=200)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('POSTED', 'Posted')], default='PENDING', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('account_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_lines', to='django_ledger.accountmodel')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_obl', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_obl', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance_lines', to='django_ledger.entitymodel')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanceApp.generalledger')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_obl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
