# Generated by Django 5.2.6 on 2026-09-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OpenBals', '0001_initial'),
        ('RecPayApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingbalanceline',
            name='trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balance_lines', to='RecPayApp.trans'),
        ),
    ]
