# Generated by Django 5.2.17 on 2026-08-28 12:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('capital_adequacy_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('liquidity_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('single_obligor_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('primary_cash_reserves', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('marketing_assets_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('top_5_depositors', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('top_5_exposures', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('liquid_asset_deposit_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_assets_shareholders_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('par_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_to_deposit_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_deposits', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_loans', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Indicator',
                'verbose_name_plural': 'Financial Indicators',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('line_description', models.CharField(blank=True, max_length=200)),
                ('ledger_updated', models.BooleanField(default=False)),
                ('member_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('open_bal_date', models.DateField(blank=True, default=None, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('period_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('year_to_date', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='coa.chartofaccounts')),
            ],
            options={
                'verbose_name_plural': 'General Ledger',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=20)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft - Not yet posted to ledger'), ('POSTED', 'Posted - Affects account balances'), ('VOID', 'Void - Cancelled')], default='DRAFT', max_length=10)),
                ('posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-entry_number'],
            },
        ),
    ]
