# Generated by Django 5.2.16 on 2026-07-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FinanceApp', '0001_initial'),
        ('MembersApp', '0001_initial'),
        ('RecPayApp', '0001_initial'),
        ('coa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='source_trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='RecPayApp.trans'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='last_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanceApp.journalentry'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='coa.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='FinanceApp.journalentry'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='MembersApp.master'),
        ),
    ]
