# Generated by Django 5.2.16 on 2026-07-22 17:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoanApp', '0001_initial'),
        ('MembersApp', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('church', 'Church'), ('school', 'School'), ('credit_union', 'Credit Union'), ('finance', 'Finance')], default='credit_union', max_length=20)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('journal_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('POSTED', 'Posted')], default='PENDING', help_text='Status for accounting integration', max_length=10)),
                ('journal_entry_id', models.CharField(blank=True, max_length=50, null=True)),
                ('rec_vou_no', models.CharField(blank=True, default='', max_length=35, null=True)),
                ('trans_no', models.CharField(blank=True, default='', max_length=35, null=True)),
                ('date', models.DateField()),
                ('trans_type', models.CharField(choices=[('Receipts', 'Receipts'), ('Payments', 'Payments')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pay_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Transfer', 'Transfer'), ('Momo', 'Mobile Money')], max_length=10)),
                ('old_trans_id', models.IntegerField(default=0)),
                ('member_no', models.IntegerField(blank=True, default=0, null=True)),
                ('member_name', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('non_member_name', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('non_member_contact', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bank_date', models.DateField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('bank_no', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_no', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('momo_no', models.CharField(blank=True, default='', max_length=50)),
                ('momo_name', models.CharField(blank=True, default='', max_length=100)),
                ('ledger_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('ledger_code', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('ledger_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('other_purpose', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('details', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('loan_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('batch_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('posted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created_by_username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='django_ledger.entitymodel')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='LoanApp.loan')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='MembersApp.master')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['rec_vou_no'], name='RecPayApp_t_rec_vou_745446_idx'), models.Index(fields=['trans_no'], name='RecPayApp_t_trans_n_ec5007_idx'), models.Index(fields=['date'], name='RecPayApp_t_date_565aa6_idx'), models.Index(fields=['trans_type'], name='RecPayApp_t_trans_t_4c1c3d_idx'), models.Index(fields=['status'], name='RecPayApp_t_status_031f76_idx'), models.Index(fields=['member'], name='RecPayApp_t_member__65daf3_idx'), models.Index(fields=['batch_number'], name='RecPayApp_t_batch_n_cf1602_idx')],
            },
        ),
    ]
