# Generated by Django 5.2.16 on 2026-07-22 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MembersApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('login_status', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('LOCKED', 'Account Locked')], default='SUCCESS', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('username_attempted', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Admin Login Histories',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='MemberLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('login_status', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('LOCKED', 'Account Locked'), ('EXPIRED', 'Session Expired')], default='SUCCESS', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='MembersApp.master')),
            ],
            options={
                'verbose_name_plural': 'Member Login Histories',
                'ordering': ['-login_time'],
            },
        ),
    ]
