# Generated by Django 5.2.17 on 2026-08-28 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginApp', '0001_initial'),
        ('MembersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberloginhistory',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='MembersApp.master'),
        ),
    ]
