# Generated by Django 5.2.17 on 2026-08-28 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20)),
                ('behavior', models.CharField(choices=[('NORMAL', 'Normal'), ('CASH', 'Cash Account'), ('BANK', 'Bank Account'), ('MOMO', 'Mobile Money'), ('SAVINGS', 'Member Savings'), ('SHARES', 'Member Shares'), ('LOAN', 'Loan Account')], default='NORMAL', max_length=20)),
                ('is_data_entry', models.BooleanField(default=False)),
                ('is_data_filled', models.BooleanField(default=False)),
                ('is_data_view', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='coa.chartofaccounts')),
            ],
            options={
                'ordering': ['accountno'],
            },
        ),
        migrations.CreateModel(
            name='AccountVisibilityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_preferences', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_preferences', to='coa.chartofaccounts')),
            ],
            options={
                'ordering': ['order', 'account__accountno'],
                'unique_together': {('user', 'account')},
            },
        ),
    ]
