# Generated by Django 5.2.6 on 2026-09-30 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(unique=True)),
                ('action', models.CharField(choices=[('PENDING', 'Awaiting human decision'), ('RELEASE', 'Released — proceed'), ('DELAY', 'Delayed — run later'), ('ABORT', 'Aborted — skip tonight')], default='PENDING', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('run_after', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_index=True, max_length=100)),
                ('kind', models.CharField(choices=[('preflight', 'Preflight'), ('main', 'Main run')], default='main', max_length=10)),
                ('run_date', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked by gate')], default='RUNNING', max_length=20)),
                ('written', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('triggered_by', models.CharField(default='cron', max_length=20)),
            ],
            options={
                'ordering': ['-run_date', 'service_name', 'kind'],
                'unique_together': {('service_name', 'kind', 'run_date')},
            },
        ),
    ]
