# Generated by Django 5.2.6 on 2026-09-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoServices', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerun',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_runs', to='django_ledger.entitymodel'),
        ),
    ]
