# Generated by Django 5.2.6 on 2026-07-30 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_users', to='django_ledger.entitymodel'),
        ),
    ]
