# Generated by Django 5.2.6 on 2026-09-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='tot_gua_given',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='tot_gua_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
