# Generated by Django 5.2.6 on 2026-07-31 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0002_master_entity'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_int_table',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sav_int', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cu_members', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
    ]
