# Generated by Django 5.2.6 on 2026-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0002_master_tot_gua_given_master_tot_gua_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='active_loan_count',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
