# Generated by Django 5.2.6 on 2026-09-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0003_master_active_loan_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='tot_interest_accrued',
        ),
    ]
