# Generated by Django 5.2.6 on 2026-07-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0003_sav_int_table_entity_alter_master_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='old_member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
