# Generated by Django 5.2.6 on 2026-09-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0004_remove_master_tot_interest_accrued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='sav_int_accrued_days',
            new_name='mnth_int_accrued_days',
        ),
    ]
