# Generated by Django 5.2.6 on 2026-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0004_alter_master_old_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
