# Generated by Django 5.2.6 on 2026-08-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0005_master_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sav_int_table',
            old_name='sav_avail_bal',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='sav_int_table',
            old_name='min_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='sav_int_table',
            name='sav_min_bal',
        ),
        migrations.RemoveField(
            model_name='sav_int_table',
            name='sav_min_days',
        ),
    ]
