# Generated by Django 5.2.6 on 2026-09-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0005_rename_sav_int_accrued_days_master_mnth_int_accrued_days'),
        ('RecPayApp', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavIntApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('DAILY', 'Daily')], default='MONTHLY', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sav_int_applications', to='django_ledger.entitymodel')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sav_int_applications', to='MembersApp.master')),
                ('trans', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sav_int_application', to='RecPayApp.trans')),
            ],
            options={
                'ordering': ['-period_end', '-id'],
                'indexes': [models.Index(fields=['master', '-period_end'], name='MembersApp__master__71dcb1_idx')],
                'unique_together': {('master', 'period_end', 'frequency')},
            },
        ),
    ]
