# Generated by Django 5.2.6 on 2026-09-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0006_savintapplication'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('old_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('effective_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('daily_interest', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('new_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mnth_accrued_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mnth_days_after', models.PositiveIntegerField(default=0)),
                ('was_month_end', models.BooleanField(default=False)),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_daily_logs', to='django_ledger.entitymodel')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_daily_logs', to='MembersApp.master')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['master', '-date'], name='MembersApp__master__7e679c_idx')],
                'unique_together': {('master', 'date')},
            },
        ),
    ]
