# Generated by Django 5.2.6 on 2026-08-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0006_rename_sav_avail_bal_sav_int_table_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sav_int_table',
            old_name='last_min_date',
            new_name='last_updated_date',
        ),
        migrations.AddField(
            model_name='sav_int_table',
            name='no_of_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
