# Generated by Django 5.2.6 on 2026-10-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0007_savingsdailylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='loan_disb_tot_princ',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='loan_last_disb_princ',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='loan_last_repayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='loan_tot_repayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
