# Generated by Django 5.2.6 on 2026-08-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0007_rename_last_min_date_sav_int_table_last_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sav_int_table',
            old_name='sav_int_calc_date',
            new_name='next_update_date',
        ),
    ]
