# Generated by Django 5.2.6 on 2026-08-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0008_rename_sav_int_calc_date_sav_int_table_next_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_int_table',
            name='update_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
