# Generated by Django 5.2.6 on 2026-08-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0009_sav_int_table_update_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_int_table',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sav_int_table',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
