# Generated by Django 5.2.6 on 2026-08-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0010_sav_int_table_applied_sav_int_table_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='sav_int_accrued_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='tot_mnth_sav_int_accrued',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
