# Generated by Django 5.2.6 on 2026-08-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MembersApp', '0011_master_sav_int_accrued_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='tot_sav_int',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
