"""
PDF reports for the ChurchApp.
Uses ReportLab — same stack as the loan schedule PDF.
"""

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_RIGHT, TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    HRFlowable,
)

from .services.contributions import (
    filtered_contributions,
    summary_by_category,
    grand_total,
)

BRAND = colors.HexColor("#1a56db")
BRAND_DARK = colors.HexColor("#1e3a5f")
GREY_BG = colors.HexColor("#f3f4f6")
GREY_LINE = colors.HexColor("#d1d5db")
GREEN_BG = colors.HexColor("#ecfdf5")
GREEN_FG = colors.HexColor("#065f46")


def _money(v):
    try:
        return f"{float(v):,.2f}"
    except Exception:
        return str(v)


def build_contribution_pdf(*, entity, member, start, end, ledger, q, generated_by=""):
    """Return PDF bytes for a filtered set of MemberContribution rows."""

    qs = filtered_contributions(
        entity, member=member, start=start, end=end, ledger_code=ledger, q=q
    )
    rows = list(qs)
    by_category = summary_by_category(qs)
    total = grand_total(qs)

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=15 * mm,
        rightMargin=15 * mm,
        topMargin=15 * mm,
        bottomMargin=20 * mm,
        title=f"Member Giving Report — {entity.name}",
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle(
        "h1",
        parent=styles["Heading1"],
        fontSize=16,
        leading=20,
        textColor=BRAND_DARK,
        spaceAfter=0,
    )
    h2 = ParagraphStyle(
        "h2", parent=styles["Normal"], fontSize=10, textColor=colors.HexColor("#6b7280")
    )
    right = ParagraphStyle(
        "right",
        parent=styles["Normal"],
        alignment=TA_RIGHT,
        fontSize=9,
        textColor=colors.HexColor("#4b5563"),
    )
    small = ParagraphStyle("small", parent=styles["Normal"], fontSize=9)
    center = ParagraphStyle(
        "center",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=8,
        textColor=colors.HexColor("#6b7280"),
    )

    story = []

    # header
    story.append(
        Table(
            [
                [
                    [
                        Paragraph(entity.name, h1),
                        Paragraph("Member Giving Report", h2),
                    ],
                    [
                        Paragraph(f"Period: {start or '—'} to {end or '—'}", right),
                        Paragraph(f"Generated by: {generated_by or '—'}", right),
                    ],
                ]
            ],
            colWidths=[110 * mm, 70 * mm],
            style=TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ]
            ),
        )
    )
    story.append(Spacer(1, 3 * mm))
    story.append(
        HRFlowable(width="100%", thickness=1.2, color=BRAND, spaceAfter=4 * mm)
    )

    # filter summary
    filters = []
    if member:
        filters.append(f"Member: <b>{member.full_name}</b>")
    if ledger:
        filters.append(f"Ledger: <b>{ledger}</b>")
    if q:
        filters.append(f"Search: <b>{q}</b>")
    if filters:
        story.append(Paragraph("    ".join(filters), small))
        story.append(Spacer(1, 3 * mm))

    # grand total tile
    story.append(
        Table(
            [
                [
                    Paragraph(
                        '<font size="9" color="#065f46"><b>GRAND TOTAL</b></font>',
                        small,
                    ),
                    Paragraph(
                        f'<font size="14" color="#065f46"><b>₵{_money(total)}</b></font>',
                        small,
                    ),
                ]
            ],
            colWidths=[120 * mm, 60 * mm],
            style=TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), GREEN_BG),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("ALIGN", (1, 0), (1, 0), "RIGHT"),
                ]
            ),
        )
    )
    story.append(Spacer(1, 5 * mm))

    # category subtotals
    if by_category:
        story.append(Paragraph("<b>Summary by Category</b>", small))
        story.append(Spacer(1, 2 * mm))

        cat_data = [["Ledger", "Category", "Count", "Total"]]
        for c in by_category:
            cat_data.append(
                [
                    c["ledger_code"] or "—",
                    c["ledger_name"] or "—",
                    str(c["count"]),
                    _money(c["total"]),
                ]
            )
        cat_tbl = Table(cat_data, colWidths=[25 * mm, 85 * mm, 20 * mm, 50 * mm])
        cat_tbl.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), GREY_BG),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
                    ("GRID", (0, 0), (-1, -1), 0.35, GREY_LINE),
                    ("LEFTPADDING", (0, 0), (-1, -1), 5),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        story.append(cat_tbl)
        story.append(Spacer(1, 6 * mm))

    # detailed rows
    story.append(Paragraph("<b>Detailed Transactions</b>", small))
    story.append(Spacer(1, 2 * mm))

    data = [["Date", "Member", "Ledger", "Receipt", "Amount"]]
    for r in rows:
        data.append(
            [
                r.date.strftime("%d %b %Y"),
                r.member.full_name,
                r.ledger_name or r.ledger_code or "—",
                r.receipt_no or "—",
                _money(r.amount),
            ]
        )
    data.append(["", "", "", "TOTAL", _money(total)])

    tbl = Table(
        data, colWidths=[25 * mm, 55 * mm, 40 * mm, 30 * mm, 30 * mm], repeatRows=1
    )
    tbl.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), GREY_BG),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("FONTSIZE", (0, 1), (-1, -1), 8.5),
                ("ALIGN", (4, 0), (4, -1), "RIGHT"),
                ("GRID", (0, 0), (-1, -1), 0.35, GREY_LINE),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("BACKGROUND", (0, -1), (-1, -1), GREY_BG),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ]
        )
    )
    story.append(tbl)
    story.append(Spacer(1, 6 * mm))
    story.append(
        Paragraph(
            "This report is computer-generated. Amounts are in Ghana Cedis (₵).",
            center,
        )
    )

    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#6b7280"))
        canvas.drawString(15 * mm, 10 * mm, f"{entity.name}  Member Giving Report")
        canvas.drawRightString(A4[0] - 15 * mm, 10 * mm, f"Page {doc.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
