# Generated by Django 5.2.16 on 2026-07-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('sort_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bic_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_no', models.CharField(max_length=50)),
                ('other_company', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('term_days', models.IntegerField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('investment_type', models.CharField(choices=[('Savings', 'Savings'), ('Fixed Deposit', 'Fixed Deposit'), ('T-Bill', 'T-Bill'), ('Call Deposit', 'Call Deposit'), ('Bonds', 'Bonds'), ('Sweep Calls', 'Sweep Calls'), ('Other', 'Other')], max_length=20)),
                ('other_investment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rollover', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('period', models.CharField(choices=[('30 day', '30 day'), ('91 day', '91 day'), ('180 day', '180 day'), ('1 year', '1 year'), ('2 year', '2 year'), ('3 year', '3 year'), ('4 year', '4 year'), ('5 year', '5 year'), ('Other', 'Other')], max_length=20)),
                ('other_period', models.CharField(blank=True, max_length=100, null=True)),
                ('interest_expected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_earned_date', models.DateField(blank=True, default=None, null=True)),
                ('discounted', models.BooleanField(default=False)),
                ('discounted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discounted_date', models.DateField(blank=True, default=None, null=True)),
                ('written_off', models.BooleanField(default=False)),
                ('written_off_date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('written off', 'Written off')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InvestApp.bank')),
            ],
        ),
    ]
