# Generated by Django 5.2.6 on 2026-08-12 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='attendance_adults',
        ),
        migrations.RemoveField(
            model_name='service',
            name='attendance_children',
        ),
        migrations.RemoveField(
            model_name='service',
            name='monthly_offering',
        ),
        migrations.RemoveField(
            model_name='service',
            name='offerings',
        ),
        migrations.RemoveField(
            model_name='service',
            name='offertory',
        ),
        migrations.RemoveField(
            model_name='service',
            name='officiating_clergy',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='weekly_offering',
        ),
        migrations.AddField(
            model_name='service',
            name='attendance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='christmas_offering',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='clergy',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='day_born_offerings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='dues',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='service',
            name='easter_offering',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='entity',
            field=models.ForeignKey(default='85346df7-dec5-46e0-94ff-b28c06169f72', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='general_offertory',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='service',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='service',
            name='guild_offerings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='harvest_offering',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='journal_entry_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_of_service',
            field=models.CharField(default='church', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='other_collections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='posted_to_ledger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='special_thank_offering',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='tithes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='service',
            name='ushers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='service',
            name='communicants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(default='2026-02-02'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guilds', to='django_ledger.entitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='Officiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officiants', to='django_ledger.entitymodel')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='officiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChurchApp.officiant'),
        ),
        migrations.CreateModel(
            name='Ushers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ushers', to='django_ledger.entitymodel')),
            ],
        ),
    ]
