# Generated by Django 5.2.6 on 2026-09-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ChurchApp', '0001_initial'),
        ('RecPayApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_activities', to='RecPayApp.trans'),
        ),
        migrations.AddField(
            model_name='service',
            name='ushers',
            field=models.ManyToManyField(blank=True, related_name='ushered_services', to='ChurchApp.member'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('entity', 'name'), name='unique_role_per_entity'),
        ),
    ]
