# Generated by Django 5.2.6 on 2026-09-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='spouse_religion',
            field=models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Moslem', 'Moslem')], default='', max_length=150, null=True),
        ),
    ]
