# Generated by Django 5.2.6 on 2026-10-01 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0002_initial'),
        ('MembersApp', '0008_alter_master_loan_disb_tot_princ_and_more'),
        ('RecPayApp', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesTithes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('dues', 'Dues'), ('tithe', 'Tithe'), ('offering', 'Offering'), ('harvest', 'Harvest'), ('christmas', 'Christmas'), ('easter', 'Easter'), ('special', 'Special Thank Offering'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('details', models.CharField(blank=True, default='', max_length=250)),
                ('receipt_no', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_tithes', to='django_ledger.entitymodel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_tithes', to='MembersApp.master')),
                ('trans', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dues_tithe', to='RecPayApp.trans')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['member', '-date'], name='ChurchApp_d_member__4c4679_idx'), models.Index(fields=['entity', '-date'], name='ChurchApp_d_entity__4d12c6_idx')],
            },
        ),
    ]
