# Generated by Django 5.2.6 on 2026-08-12 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0002_remove_service_attendance_adults_and_more'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergy',
            name='entity',
            field=models.ForeignKey(default='85346df7-dec5-46e0-94ff-b28c06169f72', on_delete=django.db.models.deletion.CASCADE, related_name='clergy', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clergy',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clergy_member', to='ChurchApp.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='entity',
            field=models.ForeignKey(default='85346df7-dec5-46e0-94ff-b28c06169f72', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officiant',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Off_member', to='ChurchApp.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='entity',
            field=models.ForeignKey(default='85346df7-dec5-46e0-94ff-b28c06169f72', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='django_ledger.entitymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to='ChurchApp.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ushers',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usher_member', to='ChurchApp.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clergy',
            name='title',
            field=models.CharField(blank=True, choices=[('Fr.', 'Fr.'), ('Can.', 'Can.'), ('Ven.', 'Ven.'), ('Bishop', 'Bishop')], default='Fr.', max_length=20, null=True),
        ),
    ]
