# Generated by Django 5.2.6 on 2026-10-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0003_duestithes'),
        ('MembersApp', '0008_alter_master_loan_disb_tot_princ_and_more'),
        ('RecPayApp', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ledger_code', models.CharField(blank=True, default='', max_length=20)),
                ('ledger_name', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.CharField(blank=True, default='', max_length=250)),
                ('receipt_no', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_contributions', to='django_ledger.entitymodel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='MembersApp.master')),
                ('trans', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='RecPayApp.trans')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['member', '-date'], name='ChurchApp_m_member__3d5723_idx'), models.Index(fields=['entity', '-date'], name='ChurchApp_m_entity__3a4ca2_idx'), models.Index(fields=['entity', 'ledger_code'], name='ChurchApp_m_entity__11c1e0_idx')],
            },
        ),
    ]
