# Generated by Django 5.2.6 on 2026-08-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0003_clergy_entity_clergy_member_member_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='guild_first',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='member',
            name='guild_second',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='member',
            name='guild_third',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
