# Generated by Django 5.2.6 on 2026-08-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0004_alter_member_guild_first_alter_member_guild_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
