# Generated by Django 5.2.6 on 2026-10-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0004_membercontribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duestithes',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues_tithes', to='ChurchApp.member'),
        ),
        migrations.AlterField(
            model_name='membercontribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='ChurchApp.member'),
        ),
    ]
