# Generated by Django 5.2.6 on 2026-08-19 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0005_member_is_deleted'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('service', 'Church Service'), ('bible_study', 'Bible Study'), ('prayer_meeting', 'Prayer Meeting'), ('youth', 'Youth Meeting'), ('children', "Children's Church"), ('choir', 'Choir Practice'), ('conference', 'Conference'), ('outreach', 'Outreach'), ('wedding', 'Wedding'), ('funeral', 'Funeral'), ('other', 'Other')], default='service', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events_attended', to='ChurchApp.member')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_events', to='django_ledger.entitymodel')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
