# Generated by Django 5.2.6 on 2026-08-20 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergy',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clergy_member', to='ChurchApp.member'),
        ),
    ]
