# Generated by Django 5.2.6 on 2026-08-20 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0007_alter_clergy_member'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('choir', 'Church Choir'), ('server', 'Server'), ('officiant', 'Officiant'), ('usher', 'Usher'), ('verger', 'Verger'), ('clergy', 'Clergy'), ('elder', 'Elder'), ('deacon', 'Deacon'), ('other', 'Other')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='django_ledger.entitymodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('date_removed', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='ChurchApp.member')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_members', to='ChurchApp.role')),
            ],
            options={
                'ordering': ['member__full_name', 'role__name'],
                'unique_together': {('member', 'role')},
            },
        ),
    ]
