# Generated by Django 5.2.6 on 2026-08-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0008_role_memberrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='members', through='ChurchApp.MemberRole', to='ChurchApp.role'),
        ),
    ]
