# Generated by Django 5.2.6 on 2026-08-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0010_alter_member_email_alter_member_father_deceased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='names_of_children',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
