# Generated by Django 5.2.6 on 2026-08-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChurchApp', '0011_alter_member_names_of_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='entity',
        ),
        migrations.DeleteModel(
            name='Guilds',
        ),
        migrations.RemoveField(
            model_name='officiant',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='officiant',
            name='member',
        ),
        migrations.RemoveField(
            model_name='service',
            name='officiant',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='member',
        ),
        migrations.RemoveField(
            model_name='ushers',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='ushers',
            name='member',
        ),
        migrations.DeleteModel(
            name='Guild',
        ),
        migrations.DeleteModel(
            name='Officiant',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Ushers',
        ),
    ]
