# Generated by Django 5.2.16 on 2026-07-22 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('super_admin', 'Super Admin')], default='user', max_length=20)),
                ('allowed_entities', models.ManyToManyField(blank=True, help_text='All entities this user can access.', related_name='allowed_users', to='django_ledger.entitymodel')),
                ('default_entity', models.ForeignKey(blank=True, help_text='The entity this user is assigned to by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='django_ledger.entitymodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='djan_led_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
