# Generated by Django 5.2.17 on 2026-08-28 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(blank=True, choices=[('church', 'Church'), ('school', 'School'), ('credit_union', 'Credit Union'), ('pos', 'POS'), ('hospital', 'Hospital'), ('hotel', 'Hotel'), ('business', 'Business'), ('ngo', 'NGO'), ('other', 'Other')], default='church', help_text='Select the type of entity', max_length=20)),
                ('max_loan_term', models.PositiveIntegerField(default=36)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('moratorium_days', models.PositiveIntegerField(default=0)),
                ('min_savings_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('savings_frequency', models.CharField(default='monthly', max_length=20)),
                ('sav_int_appl', models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('YEAR', 'YEARLY')], default='', max_length=20, null=True)),
                ('membership_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('min_shares', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('fiscal_year_start', models.DateField(blank=True, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_method', models.CharField(blank=True, default='standard', max_length=20, null=True)),
                ('savings_interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('savings_interest_application', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('savings_calc_type', models.CharField(choices=[('Simple_Sav_Interest', 'Simple'), ('Compound_Sav_Interest', 'Compound')], default='Simple_Sav_Interest', max_length=30)),
                ('last_interest_accrual_date', models.DateField(blank=True, null=True)),
                ('last_interest_accrual_run', models.DateTimeField(blank=True, null=True)),
                ('interest_expense_account_code', models.CharField(default='5020', max_length=20)),
                ('savings_interest_payable_account_code', models.CharField(default='2020', max_length=20)),
                ('loan_interest_rate', models.DecimalField(decimal_places=4, default=0, help_text='Annual interest rate (%)', max_digits=8)),
                ('loan_asset_account_code', models.CharField(default='1080', max_length=20)),
                ('loan_interest_income_code', models.CharField(default='4010', max_length=20)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='django_ledger.entitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ManualJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('debit_account_code', models.CharField(max_length=20)),
                ('credit_account_code', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted')], default='PENDING', max_length=10)),
                ('journal_entry_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_journal_entries', to='django_ledger.entitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('super_admin', 'super_admin'), ('technical', 'technical'), ('pos', 'pos'), ('school', 'school'), ('CreditUnion', 'CreditUnion'), ('Church', 'Church')], default='user', max_length=20)),
                ('account_preferences', models.JSONField(blank=True, default=dict)),
                ('allowed_entities', models.ManyToManyField(blank=True, help_text='All entities this user can access.', related_name='allowed_users', to='django_ledger.entitymodel')),
                ('default_entity', models.ForeignKey(blank=True, help_text='The entity this user is assigned to by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='django_ledger.entitymodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='djan_led_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
