# Generated by Django 5.2.6 on 2026-09-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityconfig',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('church', 'Church'), ('school', 'School'), ('credit_union', 'Credit Union'), ('pos', 'POS'), ('hospital', 'Hospital'), ('hotel', 'Hotel'), ('business', 'Business'), ('ngo', 'NGO'), ('other', 'Other')], default='church', max_length=20),
        ),
        migrations.AlterField(
            model_name='entityconfig',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entityconfig',
            name='report_subtitle',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
