# Generated by Django 5.2.6 on 2026-08-03 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0001_initial'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_loan_term', models.PositiveIntegerField(default=36)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('moratorium_days', models.PositiveIntegerField(default=0)),
                ('savings_interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('min_savings_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('savings_frequency', models.CharField(default='monthly', max_length=20)),
                ('membership_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('min_shares', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('fiscal_year_start', models.DateField(blank=True, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_method', models.CharField(blank=True, default='standard', max_length=20, null=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='django_ledger.entitymodel')),
            ],
        ),
    ]
