# Generated by Django 5.2.6 on 2026-08-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0002_entityconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityconfig',
            name='last_interest_accrual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityconfig',
            name='last_interest_accrual_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityconfig',
            name='sav_int_appl',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('YEAR', 'YEARLY')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entityconfig',
            name='savings_calc_type',
            field=models.CharField(choices=[('Simple_Sav_Interest', 'Simple'), ('Compound_Sav_Interest', 'Compound')], default='Simple_Sav_Interest', max_length=30),
        ),
        migrations.AddField(
            model_name='entityconfig',
            name='savings_interest_application',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10),
        ),
    ]
