# Generated by Django 5.2.6 on 2026-08-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0003_entityconfig_last_interest_accrual_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
