# Generated by Django 5.2.6 on 2026-08-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('super_admin', 'Super Admin'), ('pos', 'pos'), ('school', 'school'), ('Credit_Union', 'Credit_Union'), ('Church', 'Church')], default='user', max_length=20),
        ),
    ]
