# Generated by Django 5.2.6 on 2026-08-06 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0006_alter_userprofile_role'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('debit_account_code', models.CharField(max_length=20)),
                ('credit_account_code', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted')], default='PENDING', max_length=10)),
                ('journal_entry_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_journal_entries', to='django_ledger.entitymodel')),
            ],
        ),
    ]
