# Generated by Django 5.2.6 on 2026-08-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0007_manualjournalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('super_admin', 'Super Admin'), ('pos', 'pos'), ('school', 'school'), ('CreditUnion', 'CreditUnion'), ('Church', 'Church')], default='user', max_length=20),
        ),
    ]
