# Generated by Django 5.2.6 on 2026-08-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0009_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityconfig',
            name='interest_expense_account_code',
            field=models.CharField(default='5020', max_length=20),
        ),
        migrations.AddField(
            model_name='entityconfig',
            name='savings_interest_payable_account_code',
            field=models.CharField(default='2020', max_length=20),
        ),
    ]
