# Generated by Django 5.2.6 on 2026-08-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0010_entityconfig_interest_expense_account_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityconfig',
            name='loan_asset_account_code',
            field=models.CharField(default='1080', max_length=20),
        ),
        migrations.AddField(
            model_name='entityconfig',
            name='loan_interest_income_code',
            field=models.CharField(default='4010', max_length=20),
        ),
        migrations.AlterField(
            model_name='entityconfig',
            name='loan_interest_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Annual interest rate (%)', max_digits=8),
        ),
    ]
