# Generated by Django 5.2.17 on 2026-08-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0012_entityconfig_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityconfig',
            name='entity_type',
        ),
    ]
