# Generated by Django 5.2.16 on 2026-08-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan_led', '0013_remove_entityconfig_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityconfig',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('church', 'Church'), ('school', 'School'), ('credit_union', 'Credit Union'), ('pos', 'POS'), ('hospital', 'Hospital'), ('hotel', 'Hotel'), ('business', 'Business'), ('ngo', 'NGO'), ('other', 'Other')], default='church', help_text='Select the type of entity', max_length=20),
        ),
    ]
