# Generated by Django 5.2.17 on 2026-08-28 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('church_admin', 'Church Admin'), ('school_admin', 'School Admin'), ('credit_union_admin', 'Credit Union Admin'), ('diocese_admin', 'Diocese Admin'), ('finance_officer', 'Finance Officer')], default='church_admin', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('LOAN_OFFICER', 'Loan Officer'), ('AUDITOR', 'Auditor'), ('VIEWER', 'View Only')], default='VIEWER', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('account_locked', models.BooleanField(default=False)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('items_per_page', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_entities', models.ManyToManyField(blank=True, related_name='users', to='django_ledger.entitymodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_approve_loans', 'Can approve loans'), ('can_post_transactions', 'Can post transactions'), ('can_view_reports', 'Can view reports'), ('can_manage_users', 'Can manage users')],
            },
        ),
    ]
